### ISSUE TITLE
#0-6 DB강의 듣기

### ISSUE THREAD

**Issue by breakstorm** [DongHyunKims/mini-sns-dev#13]
목표 : 호눅스 NODE 강의 듣기

예상시간 : 5시간

완료조건 : 강의 시청후 강의 DB 테이블 생성 데이터 입력 삭제 조회 자료 공유하기

**Comment by wakoong** [comment]
호눅스 Basic Join 강의까지 시청 및 실습 완료

**Comment by breakstorm** [comment]
테이블 생성, 조회, 입력 실습 완료.

**Comment by wakoong** [comment]
DB 강의 완료
