### ISSUE TITLE
#0-5 DB 테이블 디자인

### ISSUE THREAD

**Issue by breakstorm** [DongHyunKims/mini-sns-dev#6]
미니SNS에서 사용할 사용자 정보 DB 테이블 설계

**Comment by breakstorm** [comment]
DB 설계를 위한 사전 필요정보 습득 필요

**Comment by breakstorm** [comment]
유저테이블 데이터정리, ERD 작성후 다시 검토하기

**Comment by DongHyunKims** [comment]
유저 테이블 설계 이슈 완료 되었나요?

**Comment by breakstorm** [comment]
유저 테이블 이슈 발견
컬럼명 오류 : USER_EAMIL, USER_PAASWARD
컬럼속성 변경 필요 : USER_NICKNAME (UNICK 속성 불필요)

**Comment by breakstorm** [comment]
회원가입 부분에서 사용자 테이블 이슈 있는것은 위에 것 외에는 없습니다.
게시판에 이슈가 없는 경우 해당 이슈는 종료하면 될것 같습니다.

**Comment by breakstorm** [comment]
해당 이슈를 종료 합니다.
